# Generated by Django 5.2 on 2026-04-22 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BajaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='Motivo de baja')),
                ('metodo_sanitizacion', models.CharField(choices=[('formateo_logico', 'Formateo lógico estándar'), ('degaussing', 'Desmagnetización (Degaussing)'), ('destruccion_fisica', 'Destrucción física'), ('factory_reset', 'Restablecimiento de fábrica')], max_length=20, verbose_name='Método de sanitización')),
                ('fase_actual', models.IntegerField(choices=[(1, 'Fase 1 — Solicitud de baja'), (2, 'Fase 2 — Ejecución de formateo / desinfección'), (3, 'Fase 3 — Destrucción física (si aplica)'), (4, 'Fase 4 — Actualización de inventario y cierre')], default=1, verbose_name='Fase actual')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('fecha_ejecucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de ejecución')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('herramienta_utilizada', models.CharField(blank=True, max_length=120, verbose_name='Herramienta utilizada')),
                ('numero_pasadas', models.PositiveSmallIntegerField(default=0, verbose_name='Número de pasadas')),
                ('verificacion_borrado', models.BooleanField(default=False, verbose_name='Verificación de borrado realizada')),
                ('evidencia_foto', models.FileField(blank=True, null=True, upload_to='bajas/evidencias/', verbose_name='Evidencia fotográfica')),
                ('acta_pdf', models.FileField(blank=True, null=True, upload_to='bajas/actas/', verbose_name='Acta de baja (PDF)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajas_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por')),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='baja', to='inventario.equipo', verbose_name='Equipo')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajas_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('testigos', models.ManyToManyField(blank=True, related_name='bajas_como_testigo', to=settings.AUTH_USER_MODEL, verbose_name='Testigos')),
            ],
            options={
                'verbose_name': 'Baja de equipo',
                'verbose_name_plural': 'Bajas de equipos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
