# Generated by Django 5.2 on 2026-04-22 17:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('usuario', models.CharField(max_length=120, verbose_name='Responsable / Custodio')),
                ('tipo', models.CharField(choices=[('desktop', 'Computadora de escritorio'), ('laptop', 'Laptop'), ('servidor', 'Servidor'), ('telefono', 'Teléfono corporativo'), ('tablet', 'Tablet'), ('usb', 'Memoria USB'), ('impresora', 'Impresora / Escáner'), ('otro', 'Otro')], default='desktop', max_length=20, verbose_name='Tipo de equipo')),
                ('marca', models.CharField(max_length=80, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=120, verbose_name='Modelo')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Número de serie')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('almacen', 'En almacén'), ('pendiente_baja', 'Pendiente de baja'), ('dado_de_baja', 'Dado de baja')], default='activo', max_length=20, verbose_name='Estado operativo')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC Address')),
                ('telefono_interno', models.CharField(blank=True, max_length=30, verbose_name='Teléfono interno')),
                ('monitores_cantidad', models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad de monitores')),
                ('monitores_marca', models.CharField(blank=True, max_length=80, verbose_name='Marca del monitor')),
                ('ubicacion', models.CharField(blank=True, max_length=120, verbose_name='Ubicación / Área')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipos/fotos/', verbose_name='Foto del equipo')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='equipos/qr/', verbose_name='Código QR')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='Fecha de adquisición')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['usuario', 'marca'],
                'indexes': [models.Index(fields=['estado'], name='inventario__estado_eb4385_idx'), models.Index(fields=['numero_serie'], name='inventario__numero__b56d38_idx'), models.Index(fields=['uuid'], name='inventario__uuid_812556_idx')],
            },
        ),
    ]
