# Generated by Django 5.2 on 2026-04-22 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=25, unique=True, verbose_name='Folio')),
                ('nombre_solicitante', models.CharField(max_length=120, verbose_name='Nombre del solicitante')),
                ('email_solicitante', models.EmailField(max_length=254, verbose_name='Correo del solicitante')),
                ('categoria', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('red', 'Red / Internet'), ('impresora', 'Impresora'), ('acceso', 'Cuenta / Acceso'), ('perifericos', 'Periféricos'), ('otro', 'Otro')], max_length=15, verbose_name='Categoría')),
                ('descripcion', models.TextField(verbose_name='Descripción del problema')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('cerrado', 'Cerrado')], default='abierto', max_length=15, verbose_name='Estado')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('notas_cierre', models.TextField(blank=True, verbose_name='Notas de cierre')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='inventario.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_apertura'],
                'indexes': [models.Index(fields=['estado'], name='tickets_tic_estado_c74d8e_idx'), models.Index(fields=['prioridad'], name='tickets_tic_priorid_554483_idx')],
            },
        ),
    ]
