# Generated by Django 5.2 on 2026-04-22 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('completo', 'Inventario completo (semestral)'), ('parcial', 'Inventario parcial (trimestral)'), ('tickets', 'Resumen de tickets'), ('mantenimiento', 'Alerta de mantenimientos'), ('extraordinario', 'Extraordinario')], max_length=20, verbose_name='Tipo')),
                ('periodo_inicio', models.DateField(blank=True, null=True, verbose_name='Periodo inicio')),
                ('periodo_fin', models.DateField(blank=True, null=True, verbose_name='Periodo fin')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Generado el')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes/', verbose_name='Archivo PDF')),
                ('enviado_por_correo', models.BooleanField(default=False, verbose_name='Enviado por correo')),
                ('destinatarios', models.JSONField(default=list, verbose_name='Destinatarios')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
