# Generated by Django 5.2 on 2026-04-22 17:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('limpieza', 'Limpieza'), ('actualizacion', 'Actualización de software')], default='preventivo', max_length=20, verbose_name='Tipo')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de mantenimiento')),
                ('proxima_fecha', models.DateField(blank=True, verbose_name='Próximo mantenimiento')),
                ('estado_equipo', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('deteriorado', 'Deteriorado')], default='bueno', max_length=15, verbose_name='Estado del equipo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='inventario.equipo', verbose_name='Equipo')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Técnico responsable')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['proxima_fecha'], name='mantenimien_proxima_b80247_idx')],
            },
        ),
    ]
